import type { Metadata } from "next";
import "./globals.css";
import {Toaster} from 'react-hot-toast';



export const metadata: Metadata = {
  title: "Shey Salon Spa App(DEV)",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       
      >
        {children}
        <Toaster />
      </body>
      
    </html>
  );
}
