import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import LayoutProvider from "@/layout-provider";

export const metadata: Metadata = {
  title: "Shey Salon Spa App(DEV)",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LayoutProvider>{children}</LayoutProvider>

        <Toaster />
      </body>
    </html>
  );
}
